name: Dependent Workflow

on:
  workflow_run:
    workflows: ["Example Workflow"]
    types:
      - completed

jobs:
  deploy_job:
    runs-on: ubuntu-latest

    steps:
      - name: Do something new here
        run: echo "Running Do something new here..."

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: example-artifact
          # Update the artifact name to match the one published in the example.yml workflow

      - name: Use output value
        run: |
          # Retrieve the output value from the artifact
          my_output=$(cat example-artifact/my_output)
          echo "Output value: $my_output"
