name: Dependent workflow

on:
  workflow_run:
    workflows: ["Example Workflow"]
    types:
      - completed

jobs:
  deploy_job:
    runs-on: ubuntu-latest

    steps:
      - name: Do something new here # Step to run tests
        run: echo "Running Do something new here..." # Placeholder command, replace with actual test commands

      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Download the artifact from the completed workflow
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: example-artifact

      - name: Use output value
        run: |
          # Retrieve the output value from the artifact
          my_output=$(cat example-artifact/my_output)
          echo "Output value: $my_output"
