name: Example Workflow  # The name of the workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the runner for this job

    steps:
    - name: Checkout Repository  # Step to check out the repository
      uses: actions/checkout@v2  # Using the actions/checkout action to fetch repository contents

    - name: Build  # Step to build the project
      run: echo "Building the project..."  # Placeholder command, replace with actual build commands

    - name: Test  # Step to run tests
      run: echo "Running tests..."  # Placeholder command, replace with actual test commands

    - name: Deploy  # Step to deploy the application
      run: echo "Deploying the application..."

    - name: Show secrets  # Step to deploy the application
      run: echo ${{ secrets.GITHUB_TOKEN }}
