name: Example Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build
        run: echo "Building the project..."
      - name: Test
        run: echo "Running tests..."
      - name: Deploy
        run: echo "Deploying the application..."
      - name: Output value
        run: |
          echo "Output value"
          echo "::set-output name=my_output::Test value"
      - name: Check GITHUB_ACTOR
        run: |
          if [ "${{ github.actor }}" == "OMC-Pree" ]; then
            echo "Running steps for Pree"
          else
            echo "Running default steps for other users"
    outputs:
      my_output: ${{ steps.build.outputs.my_output }}

  publish_artifact:
    name: Publish artifact
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: example-artifact
          path: ${{ github.workspace }}
          retention-days: 7
